Ft post service testing
2011-fakebook-project3/ng pull request #10
Opened 2021-01-04 17:00 UTC by josephtomellis

post service test complete with placeholder post service, url, and authorization dependencies

2021-01-04 17:29 UTC, yetanothersegfault commented on fakebook/karma.conf.js
> +        random: false
I would take this out of the PR. We don't need to update the karma.conf.js on the branch.

Here is a link for that
https://stackoverflow.com/questions/39459467/remove-a-modified-file-from-pull-request

2021-01-04 17:31 UTC, yetanothersegfault reviewed
If you are ready for this to go to Nick ask that he review changes on the right hand side.

But I would at least remove the change to karma.conf.js first

2021-01-05 19:59 UTC, RevatureGentry commented on fakebook/src/app/model/user.ts
> +    password: string;
Do we need to be sending the user's password from the server?

2021-01-05 20:00 UTC, RevatureGentry requested changes
LGTM - the one item I have is, does the client need to know about the user's password? Are we employing Okta here or another auth system?

2021-01-05 23:11 UTC, josephtomellis commented
The models have been cleaned up to better reflect their counterparts in the backend services. the password property was removed from the user interface, as authentication is being handled using okta.

2021-01-06 13:48 UTC, RevatureGentry approved these changes
LGTM 👍

2021-01-06 14:01 UTC, merged