Ft auth service
2011-fakebook-project3/ng pull request #20
Opened 2021-01-06 21:26 UTC by yetanothersegfault

This is the implementation of the auth service

2021-01-06 22:16 UTC, RevatureGentry reviewed
Looks fine, but my concern is by tracking if the user is authenticated in a local variable, when a user refreshes their browser - won't they need to reauthenticate, unless you also use cookies? 
Looks like there's an `isAuthenticated` method on the `OktaAuthService` - setting the local `isAuthenticated` to this result in an `ngOnInit` might better serve you in the future.

2021-01-06 22:21 UTC, escalonn requested changes, later dismissed

2021-01-06 22:21 UTC, escalonn commented on fakebook/src/app/services/auth.service.ts
> +    this.updateAuthState(isAuthenticated)
formatting

2021-01-06 22:21 UTC, escalonn commented on fakebook/src/app/services/auth.service.ts
> +      this.oktaAuth.getUser().then(console.log);
why are we doing this? this is just copy pasted code from one of my examples

2021-01-06 22:21 UTC, escalonn commented on fakebook/src/app/services/auth.service.ts
>    subscribeAuthStateChange(updateFn: (authState: boolean) => void): void {
this is not how we interact with observables, you just expose the observable object itself for others to subscribe on, we don't need to put a callback layer around the observables.

2021-01-06 22:21 UTC, escalonn commented on fakebook/src/app/services/auth.service.ts
> +    });
why should this service know or care what route to redirect to? not it's responsibility.

we can compromise process and make non major corrections to the tests in PRs like this too i guess

2021-01-08 19:28 UTC, RevatureGentry approved these changes
LGTM

2021-01-08 19:36 UTC, merged